### ISSUE TITLE
how-to for reporting

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#11]
Concern over ethical behavior, make a confidential report:
https://compliance.fiu.edu/hotline/

-data security?
-idea for improvement?
-other?

**Comment by georgebuzzell** [comment]
I think it is good to have the compliance link. However, I think we would want a protocol starting with internal reporting, no? Just thinking that there may sometimes be misunderstandings that don't need to be escalated outside the lab. I wrote an initial protocol for this. Will try to find and link here!

**Comment by jessb0t** [comment]
@georgebuzzell Totally agree.  I was dumping this into GH because I got an FIU-wide e-mail and I thought it would be good to include this information somewhere.  Please share initial protocol if you find it.  If I start working on this in detail before you find it, I will search through Drive first to see if I find your draft.

**Comment by jessb0t** [comment]
@georgebuzzell Totally agree.  I was dumping this into GH because I got an FIU-wide e-mail and I thought it would be good to include this information somewhere.  Please share initial protocol if you find it.  If I start working on this in detail before you find it, I will search through Drive first to see if I find your draft.

**Comment by jessb0t** [comment]
@georgebuzzell Totally agree.  I was dumping this into GH because I got an FIU-wide e-mail and I thought it would be good to include this information somewhere.  Please share initial protocol if you find it.  If I start working on this in detail before you find it, I will search through Drive first to see if I find your draft.

**Comment by georgebuzzell** [comment]
Here you go!

Protocol for Dealing With Alleged Violations of Trust

The current working model for dealing with violations of trust are as follows: 

1. Alleged violations of trust should be discussed (privately) with the accused first to resolve potential misunderstanding (assume mistake, not mal-intent).

2. Lab PI and/or group should be informed (privately).

3. Lab PI and/or group should investigate (as privately & as reasonably possible).
 
4. Lab PI and/or group should make a determination of whether a violation of trust occurred and also whether it was likely intentional, unintentional, intent cannot be determined, or a statement of intent is not being made (often, for our purposes, it does not matter and it is not worth bothering over).

5. Determination recorded in public-facing ledger and announced to individuals affected (this may require a small announcement to a specific  project, a lab-wide announcement, or a wider public announcement).
 
6. As part of this public facing ledger, any bans will be listed and/or whether the individual is listed as an “untrusted source”.

**Comment by jessb0t** [comment]
Closed with #56.
