### ISSUE TITLE
create default labels 

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/wiki#34]
Create an initial set of default labels and delete unneeded ones

**Comment by jessb0t** [comment]
add to sprint?
help me!

**Comment by jessb0t** [comment]
@georgebuzzell @F-said:

We can easily customize the repo default labels:
https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization
(This happens in GH, not ZH, according to the ZH documentation.)

I will need to be made an Owner in our GH org in order to implement any changes to the defaults.  Please see #41 as I think we should consider access levels more globally and carefully.

What default labels do we want?  I suggest:
- add to sprint?
- help me!

I don't find most of the GH defaults applicable to our needs, but that may be from my overly-operational perspective.  Please let me know what other labels you think would be useful and I'm happy to customize the defaults (as well as the labels on already extant repos).

Thanks!

**Comment by jessb0t** [comment]
Add these for ZH workspace filtering:

website
social-media
google-drive
hpc
github-standards
zenhub-workflow
coding-standards
